@startuml
actor Пользователь
boundary Панель
boundary Слайдер
control Settings

Пользователь -> Панель : Поставить "галочку" \nв чекбоксе "Ярлык"
note left
Показать подпись
над бегунком
end note 
Панель -> Слайдер : бегунку добавить класс\nranger__button-tip
Пользователь -> Слайдер : Переместить бегунок
Слайдер -> Слайдер : forTip()
Слайдер <- Settings : btn1_tip (btn2_tip) =\n текущее значение

@enduml